2022-04-19 16:00:28,298 ERROR: Exception on /dashboard/google [GET] [in /Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/seiscomp/webapp/dashboard/webapp/routes.py", line 118, in server
    return render_template('server.html', server=server_x, posts=posts)
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seiscomp/webapp/dashboard/webapp/templates/server.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seiscomp/webapp/dashboard/webapp/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/seiscomp/webapp/dashboard/webapp/templates/server.html", line 31, in block 'content'
    <!-- <a href="{{ url_for('edit_server') }}"> Update status </a></td> -->
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask/helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask/helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/werkzeug/routing.py", line 2315, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'edit_server'. Did you forget to specify values ['name']?
2022-04-19 16:01:42,940 ERROR: Exception on /dashboard/Bureau Maxime [GET] [in /Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/seiscomp/webapp/dashboard/webapp/routes.py", line 118, in server
    return render_template('server.html', server=server_x, posts=posts)
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seiscomp/webapp/dashboard/webapp/templates/server.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seiscomp/webapp/dashboard/webapp/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/seiscomp/webapp/dashboard/webapp/templates/server.html", line 31, in block 'content'
    <!-- <a href="{{ url_for('edit_server') }}"> Update status </a></td> -->
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask/helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/flask/helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "/Users/seiscomp/webapp/dashboard/env/lib/python3.9/site-packages/werkzeug/routing.py", line 2315, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'edit_server'. Did you forget to specify values ['name']?
2022-04-19 16:01:52,655 INFO: Dashboard startup [in /Users/seiscomp/webapp/dashboard/webapp/__init__.py:50]
2022-05-17 15:33:36,130 INFO: Dashboard startup [in /Users/seiscomp/webapp/dashboard/webapp/__init__.py:52]
2022-05-17 15:36:22,117 INFO: Dashboard startup [in /Users/seiscomp/webapp/dashboard/webapp/__init__.py:52]
2022-05-17 15:41:28,244 INFO: Dashboard startup [in /Users/seiscomp/webapp/dashboard/webapp/__init__.py:52]
2022-05-17 16:53:55,939 INFO: Dashboard startup [in /Users/seiscomp/webapp/dashboard/webapp/__init__.py:52]
2022-06-02 10:45:51,354 INFO: Dashboard startup [in /Users/seiscomp/webapp/dashboard/webapp/__init__.py:54]
2022-06-02 11:01:18,480 INFO: Dashboard startup [in /Users/seiscomp/webapp/dashboard/webapp/__init__.py:54]
2022-06-02 11:15:26,341 INFO: Dashboard startup [in /Users/seiscomp/webapp/dashboard/webapp/__init__.py:54]
2022-06-02 11:21:41,561 INFO: Dashboard startup [in /Users/seiscomp/webapp/dashboard/webapp/__init__.py:54]
2022-06-02 11:34:09,126 INFO: Dashboard startup [in /Users/seiscomp/webapp/dashboard/webapp/__init__.py:54]
2022-06-02 12:04:49,119 INFO: Dashboard startup [in /Users/seiscomp/webapp/dashboard/webapp/__init__.py:54]
2022-06-02 12:12:34,686 INFO: Dashboard startup [in /Users/seiscomp/webapp/dashboard/webapp/__init__.py:54]
2022-06-02 12:13:52,210 INFO: Dashboard startup [in /Users/seiscomp/webapp/dashboard/webapp/__init__.py:54]
2022-06-02 12:16:13,259 INFO: Dashboard startup [in /Users/seiscomp/webapp/dashboard/webapp/__init__.py:54]
2022-06-02 13:26:06,390 INFO: Dashboard startup [in /Users/seiscomp/webapp/dashboard/webapp/__init__.py:54]
2022-06-02 13:45:00,113 INFO: Dashboard startup [in /Users/seiscomp/webapp/dashboard/webapp/__init__.py:54]
2022-06-02 14:00:51,192 INFO: Dashboard startup [in /Users/seiscomp/webapp/dashboard/webapp/__init__.py:54]
2022-06-02 14:03:10,074 INFO: Dashboard startup [in /Users/seiscomp/webapp/dashboard/webapp/__init__.py:54]
2022-06-02 14:05:11,958 INFO: Dashboard startup [in /Users/seiscomp/webapp/dashboard/webapp/__init__.py:54]
2022-06-02 14:12:02,840 INFO: Dashboard startup [in /Users/seiscomp/webapp/dashboard/webapp/__init__.py:54]
2022-06-02 14:12:56,983 INFO: Dashboard startup [in /Users/seiscomp/webapp/dashboard/webapp/__init__.py:54]
2022-06-02 14:13:13,048 INFO: Dashboard startup [in /Users/seiscomp/webapp/dashboard/webapp/__init__.py:54]
2022-06-02 14:14:04,850 INFO: Dashboard startup [in /Users/seiscomp/webapp/dashboard/webapp/__init__.py:54]
2022-06-02 14:14:51,400 INFO: Dashboard startup [in /Users/seiscomp/webapp/dashboard/webapp/__init__.py:54]
2022-06-02 14:22:33,590 INFO: Dashboard startup [in /Users/seiscomp/webapp/dashboard/webapp/__init__.py:54]
2022-06-02 14:30:10,430 INFO: Dashboard startup [in /Users/seiscomp/webapp/dashboard/webapp/__init__.py:54]
2022-06-02 15:15:24,204 INFO: Dashboard startup [in /Users/seiscomp/webapp/dashboard/webapp/__init__.py:54]
